#pragma once

enum eWeaponType {
	WEAPON_TYPE_NONE = 0,
	WEAPON_TYPE_2HFIREARM,
	WEAPON_TYPE_1HFIREARM,
	WEAPON_TYPE_MELEE,
	WEAPON_TYPE_LURE
};

enum eMovementType {
	MOVEMENT_SPRINT = 0,
	MOVEMENT_1,
	MOVEMENT_2,
	MOVEMENT_WALK,
	MOVEMENT_CLIMB,
	MOVEMENT_CRAWL,
	MOVEMENT_CROUCH,
	MOVEMENT_DIVE,
	MOVEMENT_AIM,
	MOVEMENT_BLOCK,
	MOVEMENT_WALL_SQUASH,
	MOVEMENT_11,
	MOVEMENT_12,
	MOVEMENT_13,
	MOVEMENT_WALL_SQUASH2,
	MOVEMENT_15,
	MOVEMENT_16,
	MOVEMENT_17,
	MOVEMENT_DEAD_CARRY,
	MOVEMENT_19,
	MOVEMENT_CLIMBABLE_MOUNT
};